actions:
  ai:
    position: right
    command: pbpaste | aichat --code --session "$session" $(gum input --placeholder "prompt") && gum confirm "Accept suggestion?" && aichat --session "$session" --info | yq '.messages | map(select(.role == "assistant")) | .[-1].content' | gsed -i "${line_number}r /dev/stdin" $filename && bash -x helix-reload.sh $WEZTERM_PANE
  blame:
    description: Show blame for the current file and line number
    command: tig blame $filename +$line_number
    position: floating
  explorer:
    description: Open the file explorer
    position: left
    percent: 20
    command: YAZI_CONFIG_HOME=~/.config/yazi/filetree yazi
  generate_tests:
    description: Generate Go tests for the current file
    command: gotests -w -all $filename
  lazygit:
    description: Open terminal UI for git commands
    command: lazygit
    position: floating
  lint:
    description: Lint the current file
    extensions:
      go: golangci-lint run -v $filename
  mock:
    description: Generate mocks
    command: mockery --with-expecter --dir $basedir --name $interface_name
  navi:
    description: Open an interactive cheatsheet tool
    command: navi
    position: floating
  open:
    description: Open the current file and line number in the web browser
    command: helix-browse.sh $filename $line_number
  present:
    description: Present the current file
    position: window
    extensions:
      md: presenterm --theme terminal-dark $filename
  query:
    description: Query database
    command: lazysql
    position: floating
  run:
    description: Run the current file
    position: floating
    extensions:
      go: go run $basedir/*.go
      md: glow -p $filename
      rs: cargo run
  slumber:
    description: Open a HTTP client
    position: floating
    command: slumber -f ../slumber.yml
  test:
    description: Test the current file
    extensions:
      go: go test -run=$test_name -v ./$basedir/...
      hurl: hurl --test --very-verbose --color $filename
      rs: cargo test
