actions:
  ai:
    position: right
    command: cat /tmp/aichat | HX_PANE_ID=$WEZTERM_PANE hxide-aichat.sh "$session"
  blame:
    description: Show blame for the current file and line number
    command: tig blame $buffer_name +$cursor_line
    position: floating
  explorer:
    description: Open the file explorer
    position: left
    percent: 20
    command: YAZI_CONFIG_HOME=~/.config/yazi/filetree yazi
  generate_tests:
    description: Generate Go tests for the current file
    command: gotests -w -all $buffer_name
  lazygit:
    description: Open terminal UI for git commands
    command: lazygit
    position: floating
  lint:
    description: Lint the current file
    extensions:
      go: golangci-lint run -v $buffer_name
  mock:
    description: Generate mocks
    command: mockery --with-expecter --dir $basedir --name $interface_name
  navi:
    description: Open an interactive cheatsheet tool
    command: navi
    position: floating
  present:
    description: Present the current file
    position: window
    extensions:
      md: presenterm --theme terminal-dark $buffer_name
  query:
    description: Query database
    command: lazysql
    position: floating
  run:
    description: Run the current file
    position: floating
    extensions:
      go: go run $basedir/*.go
      md: glow -p $buffer_name
      rs: cargo run
      java: hxide-java.sh run $buffer_name
  slumber:
    description: Open a HTTP client
    position: floating
    command: slumber -f ../slumber.yml
  test:
    description: Test the current file
    extensions:
      go: go test -run=$test_name -v ./$basedir/...
      hurl: hurl --test --very-verbose --color $buffer_name
      rs: cargo test
      java: hxide-java.sh test $buffer_name
